# Zuul网关服务
server:
  port: 8088

spring:
  application:
    name: Zuul
  #mysql数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: gwssi
    driver-class-name: com.mysql.jdbc.Driver   #mysql驱动

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  routes:
    service-order: /service/**

